project:
  name: PerfreeBlog
  version: 1.0.0
author:
  name: Perfree
  link: https://www.yinpengfei.com
  email: perfree@126.com
## swagger配置
swagger:
  description: BootPress 接口文档
  enabled: true
  scan: com.perfree.controller

## 端口号
server:
  port: 8080

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/perfreeblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 215521..
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        config:
          enabled: true
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.perfree.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
